"""
corpus_builder_v3.py — Corpus builder for TinyGPT v3 training.

Collects, deduplicates, and filters text from multiple sources to build
a high-quality training corpus of 10-50MB. The corpus is a mix of:

  - Python source code (from the project itself + stdlib snippets)
  - English prose (project documentation, README, docstrings)
  - Russian prose (project RU documentation, comments)
  - Markdown (docs/, tutorials)

Pipeline:
  1. Collect files from the project tree (configurable globs).
  2. Filter out binary files, minified code, and boilerplate.
  3. Deduplicate lines (Jaccard similarity > threshold).
  4. Quality filter: drop lines that are too short, too repetitive,
     or have suspicious entropy (likely auto-generated).
  5. Concatenate with document separators.
  6. Return as bytes (ready for tokenization).

Usage::

    from corpus_builder_v3 import CorpusBuilder, CorpusConfig
    builder = CorpusBuilder(CorpusConfig(max_bytes=20_000_000))
    corpus = builder.build()
    print(f"Corpus: {len(corpus):,} bytes, {corpus.count(b'\\n'):,} lines")

Author: Iskhak Hamzatovich Isaev
ORCID:  0009-0003-7299-0701
License: Proprietary — All rights reserved.
"""

from __future__ import annotations

import hashlib
import math
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

import numpy as np


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
@dataclass
class CorpusConfig:
    """Configuration for the corpus builder.

    Attributes:
        max_bytes: Maximum total corpus size in bytes.
        min_file_bytes: Skip files smaller than this.
        max_file_bytes: Skip files larger than this (likely autogenerated).
        dedup_jaccard_threshold: Lines with Jaccard similarity above this
            are considered duplicates. 0.0 = no dedup.
        min_line_length: Drop lines shorter than this.
        max_line_length: Drop lines longer than this (likely minified).
        min_entropy: Drop lines with byte-entropy below this (auto-generated).
        include_patterns: Glob patterns for files to include.
        exclude_patterns: Regex patterns for paths to exclude.
        doc_separator: Bytes inserted between documents.
    """
    max_bytes: int = 20_000_000
    min_file_bytes: int = 100
    max_file_bytes: int = 500_000
    dedup_jaccard_threshold: float = 0.8
    min_line_length: int = 4
    max_line_length: int = 2000
    min_entropy: float = 2.0
    include_patterns: tuple[str, ...] = (
        "*.py", "*.md", "*.txt", "*.rst",
        "*.julia", "*.jl",
    )
    exclude_patterns: tuple[str, ...] = (
        r"/__pycache__/", r"\.pyc$", r"/\.git/",
        r"/results/", r"/\.venv/", r"/node_modules/",
        r"test_", r"_test\.",
    )
    doc_separator: bytes = b"\n\n=== DOC ===\n\n"


# ---------------------------------------------------------------------------
# Corpus builder
# ---------------------------------------------------------------------------
class CorpusBuilder:
    """Build a training corpus from the project tree.

    Args:
        config: Corpus configuration.
    """

    def __init__(self, config: CorpusConfig | None = None) -> None:
        self.config = config or CorpusConfig()
        self._seen_hashes: set[str] = set()
        self._stats: dict[str, int] = {
            "files_scanned": 0, "files_included": 0,
            "files_excluded_size": 0, "files_excluded_pattern": 0,
            "lines_total": 0, "lines_kept": 0, "lines_dedup": 0,
            "lines_filtered": 0,
        }

    # ------------------------------------------------------------------
    # File collection
    # ------------------------------------------------------------------
    def _matches_exclude(self, path: str) -> bool:
        """Check if a path matches any exclude pattern."""
        for pat in self.config.exclude_patterns:
            if re.search(pat, path):
                return True
        return False

    def collect_files(self, root: Path) -> list[Path]:
        """Collect all candidate files from ``root``.

        Args:
            root: Root directory to scan.

        Returns:
            Sorted list of file paths matching include patterns and
            passing exclude filters.
        """
        files: list[Path] = []
        for pat in self.config.include_patterns:
            for p in root.rglob(pat):
                if not p.is_file():
                    continue
                rel = str(p.relative_to(root))
                if self._matches_exclude(rel):
                    self._stats["files_excluded_pattern"] += 1
                    continue
                size = p.stat().st_size
                if size < self.config.min_file_bytes:
                    self._stats["files_excluded_size"] += 1
                    continue
                if size > self.config.max_file_bytes:
                    self._stats["files_excluded_size"] += 1
                    continue
                files.append(p)
                self._stats["files_scanned"] += 1
        return sorted(files)

    # ------------------------------------------------------------------
    # Line-level filters
    # ------------------------------------------------------------------
    @staticmethod
    def _byte_entropy(line: bytes) -> float:
        """Shannon entropy of the byte distribution in a line.

        Low entropy (< 2.0 bits/byte) suggests auto-generated or
        highly repetitive content.
        """
        if not line:
            return 0.0
        counts = np.bincount(np.frombuffer(line, dtype=np.uint8),
                             minlength=256)
        probs = counts[counts > 0] / len(line)
        return float(-np.sum(probs * np.log2(probs)))

    def _is_quality_line(self, line: bytes) -> bool:
        """Check if a line passes quality filters."""
        if len(line) < self.config.min_line_length:
            return False
        if len(line) > self.config.max_line_length:
            return False
        if self._byte_entropy(line) < self.config.min_entropy:
            return False
        return True

    @staticmethod
    def _line_fingerprint(line: bytes) -> str:
        """A normalized fingerprint for deduplication.

        We lowercase, collapse whitespace, and take the MD5 of the
        first 200 bytes (enough to catch near-duplicates).
        """
        normalized = re.sub(rb"\s+", b" ", line.lower().strip())[:200]
        return hashlib.md5(normalized).hexdigest()

    def _is_duplicate(self, line: bytes) -> bool:
        """Check if a line is a near-duplicate of one already seen."""
        fp = self._line_fingerprint(line)
        if fp in self._seen_hashes:
            return True
        self._seen_hashes.add(fp)
        return False

    # ------------------------------------------------------------------
    # Build the corpus
    # ------------------------------------------------------------------
    def build(self, roots: Iterable[Path] | None = None) -> bytes:
        """Build the corpus by scanning ``roots`` (default: project tree).

        Args:
            roots: Directories to scan. If None, auto-detect the project
                root (walk up from this file).

        Returns:
            The corpus as a single bytes object.
        """
        if roots is None:
            roots = self._auto_detect_roots()
        files: list[Path] = []
        for root in roots:
            files.extend(self.collect_files(root))

        corpus = bytearray()
        for fp in files:
            if len(corpus) >= self.config.max_bytes:
                break
            try:
                content = fp.read_bytes()
            except Exception:
                continue
            # Skip binary files (null bytes).
            if b"\x00" in content[:1024]:
                continue
            # Process line by line.
            lines = content.split(b"\n")
            kept_lines: list[bytes] = []
            for line in lines:
                self._stats["lines_total"] += 1
                if not self._is_quality_line(line):
                    self._stats["lines_filtered"] += 1
                    continue
                if self._is_duplicate(line):
                    self._stats["lines_dedup"] += 1
                    continue
                kept_lines.append(line)
                self._stats["lines_kept"] += 1
            if kept_lines:
                doc = b"\n".join(kept_lines)
                corpus.extend(doc)
                corpus.extend(self.config.doc_separator)
                self._stats["files_included"] += 1
            if len(corpus) >= self.config.max_bytes:
                break
        return bytes(corpus[:self.config.max_bytes])

    def _auto_detect_roots(self) -> list[Path]:
        """Walk up from this file to find the project root."""
        p = Path(__file__).resolve().parent
        for _ in range(6):
            if (p / "src" / "rmt_llm").is_dir() or (p / "laboratory").is_dir():
                return [p]
            if p.parent == p:
                break
            p = p.parent
        # Fallback: use the lab_en directory.
        return [Path(__file__).resolve().parent.parent]

    # ------------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------------
    @property
    def stats(self) -> dict[str, int]:
        """Return the collection/dedup statistics."""
        return self._stats.copy()

    def summary(self) -> str:
        """Human-readable summary of the last build."""
        s = self._stats
        return (
            f"Files: scanned={s['files_scanned']}, "
            f"included={s['files_included']}, "
            f"excluded(size)={s['files_excluded_size']}, "
            f"excluded(pattern)={s['files_excluded_pattern']}\n"
            f"Lines: total={s['lines_total']}, "
            f"kept={s['lines_kept']}, "
            f"dedup={s['lines_dedup']}, "
            f"filtered={s['lines_filtered']}"
        )


# ---------------------------------------------------------------------------
# Curriculum learning helpers
# ---------------------------------------------------------------------------
@dataclass
class CurriculumStage:
    """One stage of a curriculum learning schedule.

    Attributes:
        name: Stage name (for logging).
        start_epoch: First epoch of this stage.
        end_epoch: Last epoch (exclusive).
        corpus_slice: Slice of the corpus to use (start, end) in bytes.
    """
    name: str
    start_epoch: int
    end_epoch: int
    corpus_slice: tuple[int, int]


def build_curriculum(
    corpus: bytes, n_stages: int = 3, total_epochs: int = 150,
) -> list[CurriculumStage]:
    """Split the corpus into ``n_stages`` for curriculum learning.

    Stage 1 (epochs 0-33%): simplest 1/3 of corpus (shortest documents).
    Stage 2 (epochs 33-66%): medium 1/3.
    Stage 3 (epochs 66-100%): hardest 1/3 (longest documents).

    "Difficulty" is approximated by mean document length.
    """
    # Split corpus into documents by the separator.
    sep = b"\n\n=== DOC ===\n\n"
    docs = corpus.split(sep)
    docs = [d for d in docs if len(d) > 50]
    # Sort by length (shortest = easiest).
    docs.sort(key=len)
    # Split into n_stages groups.
    n = len(docs)
    chunk = max(1, n // n_stages)
    stages: list[CurriculumStage] = []
    epochs_per_stage = total_epochs // n_stages
    for i in range(n_stages):
        start_doc = i * chunk
        end_doc = (i + 1) * chunk if i < n_stages - 1 else n
        stage_corpus = sep.join(docs[start_doc:end_doc])
        # Find the byte offset of this slice in the full corpus.
        # For simplicity, we store the slice as (start_byte, end_byte)
        # of the concatenated stage corpus.
        stages.append(CurriculumStage(
            name=f"stage_{i+1}",
            start_epoch=i * epochs_per_stage,
            end_epoch=(i + 1) * epochs_per_stage if i < n_stages - 1 else total_epochs,
            corpus_slice=(0, len(stage_corpus)),
        ))
    return stages


# ---------------------------------------------------------------------------
# Quick smoke test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    print("=" * 60)
    print("CorpusBuilder v3 — smoke test")
    print("=" * 60)
    builder = CorpusBuilder(CorpusConfig(max_bytes=500_000))
    corpus = builder.build()
    print(f"\nCorpus size: {len(corpus):,} bytes")
    print(f"Lines: {corpus.count(b'\\n'):,}")
    print(f"Documents: {corpus.count(b'=== DOC ==='):,}")
    print(f"\nStats:\n{builder.summary()}")
    print(f"\nFirst 200 bytes:\n{corpus[:200]!r}")
    # Curriculum.
    stages = build_curriculum(corpus, n_stages=3, total_epochs=150)
    print(f"\nCurriculum stages: {len(stages)}")
    for s in stages:
        print(f"  {s.name}: epochs {s.start_epoch}-{s.end_epoch}, "
              f"slice={s.corpus_slice}")
